version: "3"
services:
    bryntum_pdfexport_server:
        # Helpfull to precise that to help it run on Apple ships
        platform: linux/amd64
        build: .
        image: bryntum_pdfexport_server
        container_name: bryntum_pdfexport_server
        ports:
            - "8080:8080"
            - "8081:8081"
        volumes:
            # Syncing local files with docker files to help update server files even when using docker
            - ./src:/home/pptruser/src